server:
  port: 6100

spring:
  profiles:
    active: @profileActive@
  application:
    name: monitor-admin

eureka:
  instance:
    appname: monitor-admin
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}


management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS