########################################################################
####                    spring-cloud-config配置服务中心               ####
########################################################################

server:
  port: 6001

spring:
  profiles:
    active: dev
  application:
    name: config_server

eureka:
  instance:
    appname: config_server