server:
  port: 7201

spring:
  profiles:
    active: @profileActive@
  application:
    name: user-consumer

feign:
  hystrix:
    enabled: true

hystrix:
  command:
    hystrix-command-key:
      circuit-breaker:
        sleep-window-in-milliseconds: 3000

eureka:
  instance:http://14.0.174
    appname: user-consumer
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS